version: '3.8'

services:
  client1:
    build: .
    hostname: client1
    environment:
      - CLIENT_ID=1
      - WISHLIST=7,2,9,8,1,10,5,4,6,3
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.2
    ports:
      - "5001:5001/udp"

  client2:
    build: .
    hostname: client2
    environment:
      - CLIENT_ID=2
      - WISHLIST=6,5,1,10,3,9,2,4,8,7
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.3
    ports:
      - "5002:5002/udp"

  client3:
    build: .
    hostname: client3
    environment:
      - CLIENT_ID=3
      - WISHLIST=3,7,1,6,4,9,5,2,10,8
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.4
    ports:
      - "5003:5003/udp"

  client4:
    build: .
    hostname: client4
    environment:
      - CLIENT_ID=4
      - WISHLIST=1,10,5,2,7,6,3,4,8,9
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.5
    ports:
      - "5004:5004/udp"

  client5:
    build: .
    hostname: client5
    environment:
      - CLIENT_ID=5
      - WISHLIST=2,4,5,6,7,9,10,1,8,3
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.6
    ports:
      - "5005:5005/udp"

  client6:
    build: .
    hostname: client6
    environment:
      - CLIENT_ID=6
      - WISHLIST=5,1,3,10,8,2,4,6,7,9
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.7
    ports:
      - "5006:5006/udp"

  client7:
    build: .
    hostname: client7
    environment:
      - CLIENT_ID=7
      - WISHLIST=10,9,7,2,6,1,3,5,4,8
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.8
    ports:
      - "5007:5007/udp"

  client8:
    build: .
    hostname: client8
    environment:
      - CLIENT_ID=8
      - WISHLIST=5,6,1,10,7,9,8,4,3,2
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.9
    ports:
      - "5008:5008/udp"

  client9:
    build: .
    hostname: client9
    environment:
      - CLIENT_ID=9
      - WISHLIST=10,7,9,1,3,2,5,8,4,6
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.10
    ports:
      - "5009:5009/udp"

  client10:
    build: .
    hostname: client10
    environment:
      - CLIENT_ID=10
      - WISHLIST=10,2,1,8,9,5,3,6,4,7
      - CLIENT_ADDRESSES=client1:1,client2:2,client3:3,client4:4,client5:5,client6:6,client7:7,client8:8,client9:9,client10:10
    networks:
      ttc_net:
        ipv4_address: 172.20.0.11
    ports:
      - "5010:5010/udp"

networks:
  ttc_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
